export type ConfigValueTypeName = "string" | "number" | "boolean" | "string[]";

export interface ConfigDefinition {
  envVar?: string;
  type: ConfigValueTypeName;
  default: unknown;
  group: string;
  description: string;
  sensitive?: boolean;
}

export type ConfigKey = keyof typeof CONFIG_DEFINITIONS;

export const CONFIG_DEFINITIONS = {
  strategyAdditionalContext: {
    type: "string",
    default:
      "We have an active accelerator with Microsoft in Saudi Arabia (KSA) and are prioritising work that deepens that partnership.",
    group: "strategy",
    description: "Additional narrative appended to strategic evaluation prompts (editable via admin).",
  },
  strategyFocusRegions: {
    type: "string[]",
    default: ["Saudi Arabia (KSA)", "North America"],
    group: "strategy",
    description: "Regions or markets to emphasise during strategic evaluations.",
  },
  strategyKeyInitiatives: {
    type: "string[]",
    default: ["Microsoft-led accelerators in KSA", "AI-driven automation and copilots"],
    group: "strategy",
    description: "Key initiatives the evaluation agent should reference when recommending projects.",
  },
  kbGatheringTimeoutHours: {
    envVar: "KB_GATHERING_TIMEOUT_HOURS",
    type: "number",
    default: 24,
    group: "knowledge_base",
    description: "Hours before cached KB gathering results expire.",
  },
  kbGatheringMaxAttempts: {
    envVar: "KB_GATHERING_MAX_ATTEMPTS",
    type: "number",
    default: 5,
    group: "knowledge_base",
    description: "Maximum retries when fetching KB context.",
  },
  agentProfiles: {
    envVar: "AGENT_PROFILES",
    type: "string",
    default: JSON.stringify({
      assistant: {
        minDescriptionLength: 10,
        similarCasesTopK: 3,
        maxToolIterations: 6,
        activeStates: [
          "New",
          "In Progress",
          "On Hold",
          "Pending",
          "Awaiting Info",
          "Work in Progress",
        ],
        proactiveTroubleshooting: true,
        maxClarifyingQuestions: 4,
        enableMultimodalToolResults: false,
        maxImageAttachmentsPerTool: 3,
        maxImageSizeBytes: 5242880
      },
      supervisor: {
        enabled: true,
        shadowMode: false,
        duplicateWindowMinutes: 5,
        alertChannel: "",
        llmReviewModel: "claude-sonnet-4-5"
      },
      escalation: {
        enabled: true,
        biScoreThreshold: 20,
        defaultChannel: "case-escalations",
        notifyAssignedEngineer: true,
        useLlmMessages: true
      }
    }),
    group: "agent",
    description: "Agent configuration profiles for assistant and supervisor.",
  },
  discoveryFeatures: {
    envVar: "DISCOVERY_FEATURES",
    type: "string",
    default: JSON.stringify({
      contextPackEnabled: false,
      maintenanceWindowDetection: false,
      slaChecks: true,
      highRiskCustomers: true,
      afterHours: false,
      contextCachingEnabled: true
    }),
    group: "discovery",
    description: "Discovery and policy signals feature flags.",
  },
  discoverySlackMessageLimit: {
    envVar: "DISCOVERY_SLACK_MESSAGE_LIMIT",
    type: "number",
    default: 5,
    group: "discovery",
    description: "Number of recent Slack messages to include in discovery context packs.",
  },
  discoverySimilarCasesTopK: {
    envVar: "DISCOVERY_SIMILAR_CASES_TOP_K",
    type: "number",
    default: 3,
    group: "discovery",
    description: "Number of similar cases to fetch for discovery context packs.",
  },



  discoveryContextCacheSize: {
    envVar: "DISCOVERY_CONTEXT_CACHE_SIZE",
    type: "number",
    default: 100,
    group: "discovery",
    description: "Maximum number of context packs to cache in memory.",
  },
  discoveryContextCacheTTLMinutes: {
    envVar: "DISCOVERY_CONTEXT_CACHE_TTL_MINUTES",
    type: "number",
    default: 15,
    group: "discovery",
    description: "Time-to-live for cached context packs in minutes.",
  },
  demandApiBaseUrl: {
    envVar: "DEMAND_API_BASE_URL",
    type: "string",
    default: "",
    group: "demand",
    description: "Base URL for the strategic demand request service (e.g., https://demand-app.vercel.app).",
  },
  demandApiKey: {
    envVar: "DEMAND_API_KEY",
    type: "string",
    default: "",
    group: "demand",
    description: "API key used to authenticate calls to the strategic demand request service.",
    sensitive: true,
  },
  kbSimilarCasesTopK: {
    envVar: "KB_SIMILAR_CASES_TOP_K",
    type: "number",
    default: 3,
    group: "knowledge_base",
    description: "Number of KB articles to retrieve per classification.",
  },
  caseClassificationWriteNotes: {
    envVar: "CASE_CLASSIFICATION_WRITE_NOTES",
    type: "boolean",
    default: false,
    group: "classification",
    description: "Write classification results back to ServiceNow as work notes.",
  },
  caseClassificationMaxRetries: {
    envVar: "CASE_CLASSIFICATION_MAX_RETRIES",
    type: "number",
    default: 3,
    group: "classification",
    description: "Maximum retry attempts for classification jobs.",
  },


  autoCmdbLookupEnabled: {
    envVar: "AUTO_CMDB_LOOKUP_ENABLED",
    type: "boolean",
    default: true,
    group: "cmdb",
    description: "Auto-fetch CMDB context during triage.",
  },

  cmdbReconciliationEnabled: {
    envVar: "CMDB_RECONCILIATION_ENABLED",
    type: "boolean",
    default: false,
    group: "cmdb",
    description: "Enable CMDB reconciliation workflow.",
  },
  cmdbReconciliationConfidenceThreshold: {
    envVar: "CMDB_RECONCILIATION_CONFIDENCE_THRESHOLD",
    type: "number",
    default: 0.7,
    group: "cmdb",
    description: "Minimum confidence required to reconcile CMDB records.",
  },
  cmdbReconciliationCacheResults: {
    envVar: "CMDB_RECONCILIATION_CACHE_RESULTS",
    type: "boolean",
    default: true,
    group: "cmdb",
    description: "Cache reconciliation lookups for faster repeats.",
  },
  cmdbReconciliationAssignmentGroup: {
    envVar: "CMDB_RECONCILIATION_ASSIGNMENT_GROUP",
    type: "string",
    default: "CMDB Administrators",
    group: "cmdb",
    description: "Default assignment group for CMDB reconciliation tasks.",
  },
  cmdbReconciliationSlackChannel: {
    envVar: "CMDB_RECONCILIATION_SLACK_CHANNEL",
    type: "string",
    default: "cmdb-alerts",
    group: "cmdb",
    description: "Slack channel for CMDB reconciliation notifications.",
  },
  incidentCreationAllowedGroups: {
    envVar: "INCIDENT_CREATION_ALLOWED_GROUPS",
    type: "string[]",
    default: ["Incident and Case Management"],
    group: "itsm",
    description: "Assignment groups eligible for auto incident creation.",
  },
  escalationEnabled: {
    envVar: "ESCALATION_ENABLED",
    type: "boolean",
    default: true,
    group: "triage",
    description: "Automatically escalate non-BAU cases to Slack.",
  },
  escalationBiScoreThreshold: {
    envVar: "ESCALATION_BI_SCORE_THRESHOLD",
    type: "number",
    default: 20,
    group: "triage",
    description: "Business intelligence score threshold for escalation (0-100).",
  },
  escalationDefaultChannel: {
    envVar: "ESCALATION_DEFAULT_CHANNEL",
    type: "string",
    default: "case-escalations",
    group: "triage",
    description: "Fallback Slack channel when no client-specific routing exists.",
  },
  escalationNotifyAssignedEngineer: {
    envVar: "ESCALATION_NOTIFY_ASSIGNED_ENGINEER",
    type: "boolean",
    default: true,
    group: "triage",
    description: "Mention the assigned engineer in escalation messages.",
  },
  escalationUseLlmMessages: {
    envVar: "ESCALATION_USE_LLM_MESSAGES",
    type: "boolean",
    default: true,
    group: "triage",
    description: "Use LLM-generated Slack content for escalations when available.",
  },
  githubAppId: {
    envVar: "GITHUB_APP_ID",
    type: "string",
    default: "",
    group: "github",
    description: "GitHub App identifier used for authenticated requests.",
    sensitive: true,
  },
  githubAppPrivateKey: {
    envVar: "GITHUB_APP_PRIVATE_KEY",
    type: "string",
    default: "",
    group: "github",
    description: "PEM-formatted private key for the GitHub App.",
    sensitive: true,
  },
  githubInstallationId: {
    envVar: "GITHUB_INSTALLATION_ID",
    type: "string",
    default: "",
    group: "github",
    description: "GitHub App installation id used to mint tokens.",
  },
  githubApiBaseUrl: {
    envVar: "GITHUB_API_BASE_URL",
    type: "string",
    default: "https://api.github.com",
    group: "github",
    description: "Override GitHub API base URL (set for GitHub Enterprise).",
  },
  githubFeedbackRepo: {
    envVar: "GITHUB_FEEDBACK_REPO",
    type: "string",
    default: "Mobizinc/ai-sdk-slackbot",
    group: "github",
    description: "Repository for user feedback issues (format: owner/repo).",
  },
  githubFeedbackLabels: {
    envVar: "GITHUB_FEEDBACK_LABELS",
    type: "string",
    default: "feature-request,user-feedback",
    group: "github",
    description: "Comma-separated labels to apply to feedback issues.",
  },
  llmTimeouts: {
    envVar: "LLM_TIMEOUTS",
    type: "string",
    default: JSON.stringify({
      general: 30000,
      classification: 15000,
      kbGeneration: 45000,
      escalation: 20000
    }),
    group: "llm",
    description: "LLM timeout configurations (ms) by operation type.",
  },
  catalogRedirectEnabled: {
    envVar: "CATALOG_REDIRECT_ENABLED",
    type: "boolean",
    default: false,
    group: "catalog_redirect",
    description: "Enable HR catalog redirect workflow for misrouted cases.",
  },
  catalogRedirectConfidenceThreshold: {
    envVar: "CATALOG_REDIRECT_CONFIDENCE_THRESHOLD",
    type: "number",
    default: 0.5,
    group: "catalog_redirect",
    description: "Minimum detector confidence required to trigger redirect.",
  },
  catalogRedirectAutoClose: {
    envVar: "CATALOG_REDIRECT_AUTO_CLOSE",
    type: "boolean",
    default: false,
    group: "catalog_redirect",
    description: "Automatically close cases after redirect when supported.",
  },
  catalogRedirectNotifySlack: {
    envVar: "CATALOG_REDIRECT_NOTIFY_SLACK",
    type: "boolean",
    default: false,
    group: "catalog_redirect",
    description: "Send Slack notifications when catalog redirects occur.",
  },
  supportContactInfo: {
    envVar: "SUPPORT_CONTACT_INFO",
    type: "string",
    default: "",
    group: "catalog_redirect",
    description: "Contact info added to catalog redirect work notes.",
  },
  slackSigningSecret: {
    envVar: "SLACK_SIGNING_SECRET",
    type: "string",
    default: "",
    group: "slack",
    description: "Slack signing secret used to verify incoming requests.",
    sensitive: true,
  },
  slackBotToken: {
    envVar: "SLACK_BOT_TOKEN",
    type: "string",
    default: "",
    group: "slack",
    description: "Bot token for Slack API calls.",
    sensitive: true,
  },
  servicenowEnvironment: {
    envVar: "SERVICENOW_ENVIRONMENT",
    type: "string",
    default: "prod",
    group: "servicenow",
    description: "Active ServiceNow environment (prod, uat, dev).",
  },
  servicenowEnvironments: {
    envVar: "SERVICENOW_ENVIRONMENTS",
    type: "string",
    default: JSON.stringify({
      prod: {
        instanceUrl: "",
        username: "",
        password: "",
        caseTable: "sn_customerservice_case",
        ciTable: "cmdb_ci",
        taskTable: "sn_customerservice_task",
        companyId: "",
        cloneTargetInstance: "mobizuat",
        cloneSourceInstance: "mobizprod"
      },
      uat: {
        instanceUrl: "",
        username: "",
        password: "",
        caseTable: "",
        ciTable: "cmdb_ci",
        taskTable: "sn_customerservice_task",
        companyId: ""
      },
      dev: {
        instanceUrl: "",
        username: "",
        password: "",
        caseTable: "",
        ciTable: "cmdb_ci",
        taskTable: "sn_customerservice_task"
      }
    }),
    group: "servicenow",
    description: "ServiceNow environment configurations (JSON).",
    sensitive: true,
  },

  servicenowCabSkillId: {
    envVar: "SERVICENOW_CAB_SKILL_ID",
    type: "string",
    default: "",
    group: "servicenow",
    description: "Anthropic skill ID for the ServiceNow CAB reviewer prompt bundle.",
  },
  servicenowSkillMaxIterations: {
    envVar: "SERVICENOW_SKILL_MAX_ITERATIONS",
    type: "number",
    default: 6,
    group: "servicenow",
    description: "Maximum number of Anthropic skill container turns before aborting.",
  },
  servicenowSkillTimeoutMs: {
    envVar: "SERVICENOW_SKILL_TIMEOUT_MS",
    type: "number",
    default: 30000,
    group: "servicenow",
    description: "Per-call timeout (ms) for Anthropic skill responses.",
  },
  servicenowSkillMaxTokens: {
    envVar: "SERVICENOW_SKILL_MAX_TOKENS",
    type: "number",
    default: 1024,
    group: "servicenow",
    description: "Max tokens to request per Anthropic skill call.",
  },
  servicenowApiToken: {
    envVar: "SERVICENOW_API_TOKEN",
    type: "string",
    default: "",
    group: "servicenow",
    description: "ServiceNow API token for bearer authentication.",
    sensitive: true,
  },
  servicenowCaseJournalName: {
    envVar: "SERVICENOW_CASE_JOURNAL_NAME",
    type: "string",
    default: "x_mobit_serv_case_service_case",
    group: "servicenow",
    description: "Journal field name used for case work notes.",
  },
  openaiApiKey: {
    envVar: "OPENAI_API_KEY",
    type: "string",
    default: "",
    group: "llm",
    description: "OpenAI API key used for direct or fallback requests.",
    sensitive: true,
  },
  openaiFallbackModel: {
    envVar: "OPENAI_FALLBACK_MODEL",
    type: "string",
    default: "",
    group: "llm",
    description: "Fallback OpenAI model if the primary provider fails.",
  },
  anthropicApiKey: {
    envVar: "ANTHROPIC_API_KEY",
    type: "string",
    default: "",
    group: "llm",
    description: "Anthropic provider API key.",
    sensitive: true,
  },
  anthropicModel: {
    envVar: "ANTHROPIC_MODEL",
    type: "string",
    default: "",
    group: "llm",
    description: "Default model name for the Anthropic provider.",
  },
  anthropicPromptCachingEnabled: {
    envVar: "ANTHROPIC_PROMPT_CACHING_ENABLED",
    type: "boolean",
    default: true,
    group: "llm",
    description: "Enable Anthropic prompt caching for 90% cost reduction on cached tokens.",
  },
  anthropicCachingStrategy: {
    envVar: "ANTHROPIC_CACHING_STRATEGY",
    type: "string",
    default: "system-only",
    group: "llm",
    description: "Caching strategy: 'system-only', 'system-and-tools', or 'aggressive'.",
  },
  langsmithApiKey: {
    envVar: "LANGSMITH_API_KEY",
    type: "string",
    default: "",
    group: "telemetry",
    description: "LangSmith API key for tracing LLM calls.",
    sensitive: true,
  },
  langsmithEndpoint: {
    envVar: "LANGSMITH_API_URL",
    type: "string",
    default: "",
    group: "telemetry",
    description: "LangSmith API endpoint override.",
  },
  langsmithProject: {
    envVar: "LANGSMITH_PROJECT",
    type: "string",
    default: "",
    group: "telemetry",
    description: "LangSmith project name for trace attribution.",
  },
  langsmithTracingEnabled: {
    envVar: "LANGSMITH_TRACING",
    type: "boolean",
    default: true, // Default to true - actual enablement depends on API key presence (checked at runtime)
    group: "telemetry",
    description: "Enable LangSmith tracing for LLM providers. Defaults to true, but tracing requires BOTH this flag to be true AND a valid LANGSMITH_API_KEY to be set. Set to false to explicitly disable tracing even when API key is present.",
  },
  azureSearchEndpoint: {
    envVar: "AZURE_SEARCH_ENDPOINT",
    type: "string",
    default: "",
    group: "search",
    description: "Azure Cognitive Search endpoint.",
  },
  azureSearchKey: {
    envVar: "AZURE_SEARCH_KEY",
    type: "string",
    default: "",
    group: "search",
    description: "Azure Cognitive Search API key.",
    sensitive: true,
  },
  azureSearchIndexName: {
    envVar: "AZURE_SEARCH_INDEX_NAME",
    type: "string",
    default: "",
    group: "search",
    description: "Default index name for Azure Cognitive Search.",
  },
  caseEmbeddingModel: {
    envVar: "CASE_EMBEDDING_MODEL",
    type: "string",
    default: "",
    group: "llm",
    description: "Model identifier used for embedding case content.",
  },
  qstashToken: {
    envVar: "QSTASH_TOKEN",
    type: "string",
    default: "",
    group: "queue",
    description: "Upstash QStash token for async job scheduling.",
    sensitive: true,
  },
  qstashCurrentSigningKey: {
    envVar: "QSTASH_CURRENT_SIGNING_KEY",
    type: "string",
    default: "",
    group: "queue",
    description: "Current signing key from Upstash QStash for webhook verification.",
    sensitive: true,
  },
  qstashNextSigningKey: {
    envVar: "QSTASH_NEXT_SIGNING_KEY",
    type: "string",
    default: "",
    group: "queue",
    description: "Next signing key from Upstash QStash for upcoming rotation.",
    sensitive: true,
  },
  webexConfig: {
    envVar: "WEBEX_CONFIG",
    type: "string",
    default: JSON.stringify({
      accessToken: "",
      clientId: "",
      clientSecret: "",
      refreshToken: "",
      orgId: "",
      baseUrl: "https://webexapis.com",
      tasksPath: "v1/tasks",
      tokenUrl: "https://webexapis.com/v1/access_token"
    }),
    group: "webex",
    description: "Webex Contact Center integration configuration.",
    sensitive: true,
  },
  relayWebhookSecret: {
    envVar: "RELAY_WEBHOOK_SECRET",
    type: "string",
    default: "",
    group: "integrations",
    description: "Shared secret for Relay webhook verification.",
    sensitive: true,
  },
  exaApiKey: {
    envVar: "EXA_API_KEY",
    type: "string",
    default: "",
    group: "integrations",
    description: "API key for Exa search service.",
    sensitive: true,
  },
  caseWorkflowRouting: {
    envVar: "CASE_WORKFLOW_ROUTING",
    type: "string",
    default: "",
    group: "workflow",
    description: "JSON configuration for workflow routing rules.",
  },
  caseWorkflowPrompts: {
    envVar: "CASE_WORKFLOW_PROMPTS",
    type: "string",
    default: "",
    group: "workflow",
    description: "JSON configuration for workflow-specific prompt overrides.",
  },
  systemicPatternWithinDays: {
    envVar: "SYSTEMIC_PATTERN_WITHIN_DAYS",
    type: "number",
    default: 14,
    group: "classification",
    description: "Number of days considered for systemic pattern detection.",
  },
  mobizServiceDeskDomains: {
    envVar: "MOBIZ_SERVICE_DESK_DOMAINS",
    type: "string",
    default: "",
    group: "filters",
    description: "Comma-separated list of service desk domains for Mobiz filtering.",
  },
  hrRequestDetectorConfig: {
    envVar: "HR_REQUEST_DETECTOR_CONFIG",
    type: "string",
    default: "",
    group: "catalog_redirect",
    description: "JSON configuration overrides for HR request detector mappings.",
  },
  azureSqlDatabaseUrl: {
    envVar: "AZURE_SQL_DATABASE_URL",
    type: "string",
    default: "",
    group: "database",
    description: "Connection string for Azure SQL (sensitive).",
    sensitive: true,
  },
  adminApiKey: {
    envVar: "ADMIN_API_KEY",
    type: "string",
    default: "",
    group: "admin",
    description: "Shared secret for admin metrics endpoints.",
    sensitive: true,
  },
  adminApiToken: {
    envVar: "NEXT_PUBLIC_ADMIN_TOKEN",
    type: "string",
    default: "",
    group: "admin",
    description: "Authentication token for all admin API endpoints (business contexts, config, reports, etc.).",
    sensitive: true,
  },
  callSyncLookbackMinutes: {
    envVar: "CALL_SYNC_LOOKBACK_MINUTES",
    type: "number",
    default: 15,
    group: "integrations",
    description: "Minutes to look back when syncing Webex voice interactions.",
  },
  caseQueueChannelId: {
    envVar: "CASE_QUEUE_CHANNEL_ID",
    type: "string",
    default: "",
    group: "slack",
    description: "Slack channel ID used for case queue reporting.",
  },
  customerAccountNumber: {
    envVar: "CUSTOMER_ACCOUNT_NUMBER",
    type: "string",
    default: "",
    group: "clients",
    description: "Default customer account number used in scripts and onboarding.",
  },
  databaseUrl: {
    envVar: "DATABASE_URL",
    type: "string",
    default: "",
    group: "database",
    description: "Primary Postgres connection string.",
    sensitive: true,
  },

  dryRun: {
    envVar: "DRY_RUN",
    type: "boolean",
    default: true,
    group: "scripts",
    description: "When true (default), scripts operate in dry-run mode unless explicitly disabled.",
  },
  enableAsyncTriage: {
    envVar: "ENABLE_ASYNC_TRIAGE",
    type: "boolean",
    default: false,
    group: "triage",
    description: "Enable async triage processing queue.",
  },
  enableCaseClassification: {
    envVar: "ENABLE_CASE_CLASSIFICATION",
    type: "boolean",
    default: false,
    group: "classification",
    description: "Allow automatic case classification (legacy toggle).",
  },
  eventGridCaseEventsEndpoint: {
    envVar: "EVENT_GRID_CASE_EVENTS_ENDPOINT",
    type: "string",
    default: "",
    group: "integrations",
    description: "Azure Event Grid endpoint for case events.",
  },
  eventGridCaseEventsKey: {
    envVar: "EVENT_GRID_CASE_EVENTS_KEY",
    type: "string",
    default: "",
    group: "integrations",
    description: "Azure Event Grid access key for case events.",
    sensitive: true,
  },
  idempotencyWindowMinutes: {
    envVar: "IDEMPOTENCY_WINDOW_MINUTES",
    type: "number",
    default: 10,
    group: "triage",
    description: "Minutes to enforce idempotency for async triage payloads.",
  },
  incidentAutoCloseLimit: {
    envVar: "INCIDENT_AUTO_CLOSE_LIMIT",
    type: "number",
    default: 50,
    group: "incident_management",
    description: "Maximum incidents to auto-close per cron run.",
  },
  incidentAutoCloseMinutes: {
    envVar: "INCIDENT_AUTO_CLOSE_MINUTES",
    type: "number",
    default: 60,
    group: "incident_management",
    description: "Minutes to wait before auto-closing resolved incidents.",
  },
  incidentAutoCloseCode: {
    envVar: "INCIDENT_AUTO_CLOSE_CODE",
    type: "string",
    default: "Resolved - Awaiting Confirmation",
    group: "incident_management",
    description: "Close code used when auto-closing incidents.",
  },
  mobizLeaderboardChannel: {
    envVar: "MOBIZ_LEADERBOARD_CHANNEL",
    type: "string",
    default: "",
    group: "slack",
    description: "Slack channel ID for Mobiz service desk leaderboard posts.",
  },
  staleCaseNetworkChannel: {
    envVar: "STALE_CASE_NETWORK_CHANNEL_ID",
    type: "string",
    default: "C045N8WF3NE",
    group: "slack",
    description: "Slack channel ID for Network Engineers stale case follow-up notifications.",
  },
  staleCaseIcmChannel: {
    envVar: "STALE_CASE_ICM_CHANNEL_ID",
    type: "string",
    default: "C01FFQTMAD9",
    group: "slack",
    description: "Slack channel ID for Incident and Case Management stale case follow-up notifications.",
  },
  nextPublicAdminToken: {
    envVar: "NEXT_PUBLIC_ADMIN_TOKEN",
    type: "string",
    default: "",
    group: "admin_ui",
    description: "Public admin token exposed to the admin UI.",
  },
  nextPublicApiBaseUrl: {
    envVar: "NEXT_PUBLIC_API_BASE_URL",
    type: "string",
    default: "",
    group: "admin_ui",
    description: "Override API base URL for the admin UI (useful in development).",
  },

  servicenowWebhookSecret: {
    envVar: "SERVICENOW_WEBHOOK_SECRET",
    type: "string",
    default: "",
    group: "servicenow",
    description: "Shared secret for validating ServiceNow webhook requests.",
    sensitive: true,
  },
  testCaseNumber: {
    envVar: "TEST_CASE_NUMBER",
    type: "string",
    default: "",
    group: "testing",
    description: "Default case number used in test scripts.",
  },

  vercelEnv: {
    envVar: "VERCEL_ENV",
    type: "string",
    default: "",
    group: "platform",
    description: "Vercel environment indicator (production, preview, development).",
  },
  vercelOidcToken: {
    envVar: "VERCEL_OIDC_TOKEN",
    type: "string",
    default: "",
    group: "platform",
    description: "Vercel OIDC token for secure builds/deployments.",
    sensitive: true,
  },
  vercelUrl: {
    envVar: "VERCEL_URL",
    type: "string",
    default: "",
    group: "platform",
    description: "Vercel provided deployment URL.",
  },
  worknoteLookbackMinutes: {
    envVar: "WORKNOTE_LOOKBACK_MINUTES",
    type: "number",
    default: 60,
    group: "integrations",
    description: "Minutes lookback when syncing voice worknotes.",
  },

  muscleMemoryCollectionEnabled: {
    envVar: "MUSCLE_MEMORY_COLLECTION_ENABLED",
    type: "boolean",
    default: false,
    group: "muscle_memory",
    description: "Enable automatic collection of high-quality agent interactions as muscle memory exemplars.",
  },
  muscleMemoryRetrievalEnabled: {
    envVar: "MUSCLE_MEMORY_RETRIEVAL_ENABLED",
    type: "boolean",
    default: false,
    group: "muscle_memory",
    description: "Enable semantic retrieval of muscle memory exemplars in discovery context packs.",
  },
  muscleMemoryTopK: {
    envVar: "MUSCLE_MEMORY_TOP_K",
    type: "number",
    default: 3,
    group: "muscle_memory",
    description: "Maximum number of similar exemplars to retrieve for context enrichment.",
  },
  muscleMemoryMinQuality: {
    envVar: "MUSCLE_MEMORY_MIN_QUALITY",
    type: "number",
    default: 0.7,
    group: "muscle_memory",
    description: "Minimum quality score (0.0-1.0) for exemplars to be included in retrieval results.",
  },
  muscleMemoryQualityThreshold: {
    envVar: "MUSCLE_MEMORY_QUALITY_THRESHOLD",
    type: "number",
    default: 0.6,
    group: "muscle_memory",
    description: "Minimum quality score (0.0-1.0) required for an interaction to be stored as an exemplar.",
  },
} as const satisfies Record<string, ConfigDefinition>;

type ValueType<T extends ConfigDefinition["type"]> = T extends "boolean"
  ? boolean
  : T extends "number"
    ? number
    : T extends "string[]"
      ? string[]
      : string;

export type ConfigValueMap = {
  [K in ConfigKey]: ValueType<(typeof CONFIG_DEFINITIONS)[K]["type"]>;
};
